# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
 - libproj-dev
 - libgdal-dev
 - libgeos++-dev
 - libgeos-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:marlam/gta
  - sudo apt-get update -qq
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

after_success:
  - Rscript -e 'covr::codecov()'


