# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
  - libudunits2-dev libproj-dev libgeos++-dev libgdal-dev


# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

after_success:
  - Rscript -e 'covr::codecov()'


