# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
 - libhdf5-serial-dev
 - libproj-dev
 - libgdal-dev
 - libgeos++-dev

before_install:
  - "export RGL_USE_NULL=TRUE"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

after_success:
  - Rscript -e 'covr::codecov()'


